const terms = {
  title: "Política de Privadesa",
  parraf1: "Aquesta Política de Privadesa estableix els termes en què Fermaterra utilitza i protegeix la informació que és proporcionada pels seus usuaris al moment d'utilitzar el seu lloc web. Aquesta companyia està compromesa amb la seguretat de les dades dels usuaris. Quan us demanem omplir els camps d'informació personal amb la qual pugueu ser identificat, ho fem assegurant que només s'emprarà d'acord amb els termes d'aquest document. No obstant això, aquesta Política de Privadesa pot canviar amb el temps o ser actualitzada pel que us recomanem i emfatitzem revisar contínuament aquesta pàgina per assegurar-se que està d'acord amb aquests canvis.",
  subtitle1: "Informació que es recull",
  parraf2: "El nostre lloc web podrà recollir informació personal per exemple: Nom, informació de contacte com la vostra adreça de correu electrònic i informació demogràfica. Així mateix quan sigui necessari podrà ser requerida informació específica per processar alguna comanda o realitzar un lliurament o facturació",
  subtitle2: "Ús de la informació recollida",
  parraf3: "El nostre lloc web empra la informació per tal de proporcionar el millor servei possible, particularment per mantenir un registre dusuaris, de comandes en cas que apliqui, i millorar els nostres productes i serveis. És possible que siguin enviats correus electrònics periòdicament a través del nostre lloc amb ofertes especials, nous productes i altra informació publicitària que considerem rellevant per a vostè o que pugui brindar algun benefici, aquests correus electrònics seran enviats a l'adreça que vostè proporcioni i podran ser cancel·lats en qualsevol moment.",
  parraf4: "Fermaterra està altament compromès per complir amb el compromís de mantenir la vostra informació segura. Fem servir els sistemes més avançats i els actualitzem constantment per assegurar-nos que no hi hagi cap accés no autoritzat.",
  subtitle3: "Galetes",
  parraf5: "Una galeta es refereix a un fitxer que és enviat amb la finalitat de sol·licitar permís per emmagatzemar-se al vostre ordinador, en acceptar aquest fitxer es crea i la galeta serveix llavors per tenir informació respecte al trànsit web, i també facilita les futures visites a una web recurrent. Una altra funció que tenen les cookies és que amb elles les web et poden reconèixer individualment i per tant oferir-te el millor servei personalitzat de la seva web.",
  parraf6: "El nostre lloc web empra les galetes per poder identificar les pàgines que són visitades i la seva freqüència. Aquesta informació és emprada únicament per a anàlisi estadística i després la informació s'elimina de forma permanent. Vostè pot eliminar les galetes en qualsevol moment des del seu ordinador. Sense no obstant això, les cookies ajuden a proporcionar un millor servei dels llocs web, estàs no donen accés a informació del seu ordinador ni de vostè, a menys que vostè així ho vulgui i la proporcioni directament. no obstant això la majoria de navegadors accepten cookies automàticament ja que serveix per tenir un millor servei web. També vostè pot canviar la configuració del seu ordinador per declinar les cookies. Si es declinen és possible que no pugui utilitzar alguns dels nostres serveis.",
  subtitle4: "Enllaços a Tercers",
  parraf7: "Aquest lloc web podria contenir enllaços a altres llocs que puguin ser del seu interès. Quan feu clic en aquests enllaços i abandoneu la nostra pàgina, ja no tenim control sobre el lloc al qual és redirigit i per tant no som responsables dels termes o privadesa ni de la protecció de les seves dades en aquests altres llocs tercers. Aquests llocs estan subjectes a les seves pròpies polítiques de privadesa per la qual cosa és recomanable que els consulteu per confirmar que vostè està d'acord amb aquestes.",
  subtitle5: "Control de la vostra informació personal",
  parraf8: "En qualsevol moment vostè pot restringir la recopilació o lús de la informació personal que és proporcionada al nostre lloc web. Cada vegada que se us demani omplir un formulari, com el d'alta d'usuari, podeu marcar o desmarcar l'opció de rebre informació per correu electrònic. En cas que hagueu marcat l'opció de rebre el nostre butlletí o publicitat podeu cancel·lar-la en qualsevol moment.",
  parraf9: "Aquesta companyia no vendrà, cedirà ni distribuirà la informació personal que és recopilada sense el seu consentiment, llevat que sigui requerit per un jutge amb una ordre judicial.",
  parraf10: "Fermaterra es reserva el dret de canviar els termes de la present Política de Privadesa en qualsevol moment."

};

module.exports = terms;
